'\" t
.\"     Title: pdf2djvu
.\"    Author: Jakub Wilk <jwilk@jwilk.net>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09.08.2022
.\"    Manual: руководство по pdf2djvu
.\"    Source: pdf2djvu 0.9.19
.\"  Language: Russian
.\"
.TH "pdf2djvu" "1" "09.08.2022" "pdf2djvu 0\&.9\&.19" "руководство по pdf2djvu"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
pdf2djvu \- создаёт DjVu\-файлы из PDF\-файлов
.SH "СИНТАКСИС"
.HP \w'\fBpdf2djvu\fR\ 'u
\fBpdf2djvu\fR [{\fB\-o\fR\ |\ \fB\-\-output\fR}\ \fIрезультирующий\-djvu\-файл\fR] [\fIпараметр\fR...] \fIpdf\-файл\fR...
.HP \w'\fBpdf2djvu\fR\ 'u
\fBpdf2djvu\fR {\fB\-i\fR\ |\ \fB\-\-indirect\fR}\ \fIфайл\-индекса\-djvu\fR  [\fIпараметр\fR...] \fIpdf\-файл\fR...
.HP \w'\fBpdf2djvu\fR\ 'u
\fBpdf2djvu\fR {\fB\-\-version\fR | \fB\-\-help\fR | \fB\-h\fR}
.SH "ОПИСАНИЕ"
.PP
Программа создаёт DjVu\-файл из одного или нескольких Portable Document Format файлов\&.
.SH "ПАРАМЕТРЫ"
.PP
\fBpdf2djvu\fR
допускает следующие параметры:
.SS "Тип документа, имена файлов"
.PP
\fB\-o\fR, \fB\-\-output=\fR\fB\fIрезультирующий\-djvu\-файл\fR\fR
.RS 4
Создать объединённый многостраничный документ\&. Записать файл в
\fIрезультирующий\-djvu\-файл\fR
вместо стандартного вывода\&.
.RE
.PP
\fB\-i\fR, \fB\-\-indirect=\fR\fB\fIфайл\-индекса\-djvu\fR\fR
.RS 4
Создать раздельный многостраничный документ\&. Использовать
\fIфайл\-индекса\-djvu\fR
как имя файла индекса; поместить файлы\-компоненты в один и тот же каталог\&. Каталог должен существовать и иметь разрешение на запись\&.
.RE
.PP
\fB\-\-page\-id\-template=\fR\fB\fIшаблон\fR\fR
.RS 4
Устанавливает схему именования идентификаторов страниц\&. Обратитесь за справкой к
\(FoЯЗЫК ШАБЛОНОВ\(Fc
секции описания языка шаблонов\&.
.sp
Шаблон по умолчанию
\(Fop{page:04*}\&.djvu\(Fc\&.
.sp
По причине портабельности идентификатор страницы:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
должен состоять только из строчных ASCII букв, цифр,
_,
+,
\-
и точки,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
не может начинаться с
+,
\-
или точки,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
не может включать две последовательные точки,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
должен заканчиваться расширением
\&.djvu
или
\&.djv\&.
.RE
.sp
.RE
.PP
\fB\-\-page\-id\-prefix=\fR\fB\fIпрефикс\fR\fR
.RS 4
Эквивалентно
\(Fo\-\-page\-id\-template=\fIпрефикс\fR{page:04*}\&.djvu\(Fc\&.
.RE
.PP
\fB\-\-page\-title\-template=\fR\fB\fIшаблон\fR\fR
.RS 4
Устанавливает шаблон заголовков страниц\&. Обратитесь за справкой к секции описания языка шаблонов
\(FoЯЗЫК ШАБЛОНОВ\(Fc\&.
.sp
Шаблон по умолчанию
\(Fo{label}\(Fc\&.
.RE
.PP
\fB\-\-no\-page\-titles\fR
.RS 4
Не устанавливать заголовки страницы\&.
.RE
.SS "Разрешение, размер страницы"
.PP
\fB\-d\fR, \fB\-\-dpi=\fR\fB\fIразрешение\fR\fR
.RS 4
Устанавливает желаемое разрешение
\fIразрешение\fR
точек на дюйм\&. По умолчанию 300 dpi\&. Разрешённый диапазон: 72 \(<=
\fIразрешение\fR
\(<= 6000\&.
.RE
.PP
\fB\-\-media\-box\fR
.RS 4
Использовать
MediaBox
для определения размера страницы\&. По умолчанию используется
CropBox\&.
.RE
.PP
\fB\-\-page\-size=\fR\fB\fIширина\fR\fR\fBx\fR\fB\fIвысота\fR\fR
.RS 4
Устанавливает предпочитаемый размер страницы в
\fIширина\fR
пикселов \(mu
\fIвысота\fR
пикселов\&. Действительный размер страницы может изменяться для соблюдения соотношения и из\-за ограничений DjVu\&. (Этот параметр имеет приоритет над
\fB\-d\fR/\fB\-\-dpi\fR\&.)
.RE
.PP
\fB\-\-guess\-dpi\fR
.RS 4
Попробовать предположить оригинальное разрешение проверяя внедрённые изображения\&. Используйте с осторожностью\&.
.RE
.SS "Качество изображения"
.PP
\fB\-\-bg\-slices=\fR\fB\fIn\fR\fR\fB+\fR\fB\fI\&...\fR\fR\fB+\fR\fB\fIn\fR\fR, \fB\-\-bg\-slices=\fR\fB\fIn\fR\fR\fB,\fR\fB\fI\&...\fR\fR\fB,\fR\fB\fIn\fR\fR
.RS 4
Устанавливает качество кодирования фонового слоя IW44\&. Этот параметр похож на параметр
\fB\-slice\fR
для
\fBc44\fR\&. Обратитесь за справкой к man\-странице
\fBc44\fR(1)\&. По умолчанию
72+11+10+10\&.
.RE
.PP
\fB\-\-bg\-subsample=\fR\fB\fIn\fR\fR
.RS 4
Устанавливает отношение подвыборки фона\&. По умолчанию 3\&. Допустимые значения находятся между 1 и 12 включительно\&.
.RE
.PP
\fB\-\-fg\-colors=default\fR
.RS 4
Попробовать сохранить все цвета переднего плана\&. Используется по умолчанию\&.
.RE
.PP
\fB\-\-fg\-colors=web\fR
.RS 4
Уменьшить количество цветов переднего плана до web\-палитры (216 цветов)\&. Не рекомендуется использовать\&.
.RE
.PP
\fB\-\-fg\-colors=\fR\fB\fIn\fR\fR
.RS 4
Использует GraphicsMagick для уменьшения количества явных цветов в слое переднего плана\&. Допустимые значения от 1 до 4080\&. Не рекомендуется использовать\&.
.RE
.PP
\fB\-\-fg\-colors=black\fR
.RS 4
Не использовать любую информацию о цветах из слоя переднего плана\&.
.RE
.PP
\fB\-\-monochrome\fR
.RS 4
Рендерить страницы как монохромные изображения\&. С этим параметром опции
\fB\-\-bg\-\fR\fB\fI\&...\fR\fR
и
\fB\-\-fg\-\fR\fB\fI\&...\fR\fR
не принимаются во внимание\&.
.RE
.PP
\fB\-\-loss\-level=\fR\fB\fIn\fR\fR
.RS 4
Устанавливает агрессивность компрессии с потерями\&. По умолчанию 0 (без потерь)\&. Допустимые значения от 0 до 200 включительно\&. Этот параметр похож на параметр
\fB\-losslevel\fR
для
\fBcjb2\fR\&. Обратитесь за справкой к man\-странице
\fBcjb2\fR(1)\&. Этот параметр принимается во внимание только вместе с параметром
\fB\-\-monochrome\fR\&.
.RE
.PP
\fB\-\-lossy\fR
.RS 4
Равносильно
\fB\-\-loss\-level=100\fR\&.
.RE
.PP
\fB\-\-anti\-alias\fR
.RS 4
Разрешить сглаживание шрифтов и векторной графики\&. Не рекомендуется использовать\&.
.RE
.SS "Извлечение"
.PP
\fB\-\-no\-metadata\fR
.RS 4
Не извлекать метаданные\&.
.sp
По умолчанию:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Извлекаются следующие значения информации документа:
Title,
Author,
Subject,
Creator,
Producer,
CreationDate,
ModDate\&. Временные отметки форматируются согласно стандарту
\m[blue]\fBRFC 3999\fR\m[]\&\s-2\u[1]\d\s+2\&. Дата и время разделены одиночным пробелом\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Соответственно извлекаются (или создаются) и обновляются метаданные XMP\&.
.RE
.sp
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBПримечание\fR
.ps -1
.br
В случае нескольких входных документов используются только метаданные из первого\&.
.sp .5v
.RE
.RE
.PP
\fB\-\-verbatim\-metadata\fR
.RS 4
Сохранять метаданные нетронутыми\&.
.RE
.PP
\fB\-\-no\-outline\fR
.RS 4
Не извлекать оглавление документа\&.
.RE
.PP
\fB\-\-hyperlinks=border\-avis\fR
.RS 4
Делать границы ссылок всегда видимыми\&.
.sp
По умолчанию границы ссылок становятся видимыми только при наведении на ссылку мыши\&.
.RE
.PP
\fB\-\-hyperlinks=#\fR\fB\fIRRGGBB\fR\fR
.RS 4
Принудительно использовать заданный цвет для границы ссылок\&.
.RE
.PP
\fB\-\-no\-hyperlinks\fR, \fB\-\-hyperlinks=none\fR
.RS 4
Не извлекать ссылки\&.
.RE
.PP
\fB\-\-no\-text\fR
.RS 4
Не извлекать текст\&.
.RE
.PP
\fB\-\-words\fR
.RS 4
Извлечь текст\&. Записать расположение каждого слова\&. Используется по умолчанию\&.
.RE
.PP
\fB\-\-lines\fR
.RS 4
Извлечь текст\&. Записать расположение каждой строки, а не слова\&.
.RE
.PP
\fB\-\-crop\-text\fR
.RS 4
Не извлекать текст, который находится за пределами страницы\&.
.RE
.PP
\fB\-\-no\-nfkc\fR
.RS 4
Не применять
\m[blue]\fBNFKC\fR\m[]\&\s-2\u[2]\d\s+2
нормализацию к тексту за исключением символов из
\m[blue]\fBAlphabetic Presentation Forms block\fR\m[]\&\s-2\u[3]\d\s+2
(U+FB00\(enU+FB4F), которые нормализованы безоговорочно\&.
.sp
По умолчанию применяется NFKC нормализация для всех символов\&.
.RE
.PP
\fB\-\-filter\-text=\fR\fB\fIкомандная строка\fR\fR
.RS 4
Фильтровать текст через
\fIкомандная строка\fR\&. Данный фильтр должен сохранить пробелы, управляющие символы и десятичные цифры\&.
.sp
Этот параметр подразумевает
\fB\-\-no\-nfkc\fR\&.
.RE
.PP
\fB\-p\fR, \fB\-\-pages=\fR\fB\fIдиапазон\-страниц\fR\fR
.RS 4
Устанавливает страницы для конвертирования\&.
\fIдиапазон\-страниц\fR
\(em это разделяемый запятыми список поддиапазонов\&. Каждый поддиапазон является одиночной страницей (например,
17) или последовательным диапазоном страниц (например,
37\-42)\&. Повторяющиеся номера страниц не допускаются\&. Страницы нумеруются с 1\&.
.sp
По умолчанию конвертируются все страницы\&.
.RE
.SS "Производительность"
.PP
\fB\-j\fR, \fB\-\-jobs=\fR\fB\fIn\fR\fR
.RS 4
Использовать
\fIn\fR
потоков для конвертации\&. По умолчанию используется один поток\&.
.RE
.PP
\fB\-j0\fR, \fB\-\-jobs=0\fR
.RS 4
Определить автоматически, сколько потоков использовать для конвертации\&.
.RE
.SS "Подробности, справка"
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Показывать больше информационных сообщений при конвертации файла\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Не показывать информационные сообщения при конвертации файла\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Вывести информацию о версии и выйти\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать справку и выйти\&.
.RE
.SH "ОКРУЖЕНИЕ"
.PP
Следующие переменные окружения оказывают влияние на
\fBpdf2djvu\fR
в Unix\-системах:
.PP
\fIOMP_\fR\fI\fI*\fR\fR
.RS 4
Поведением, с точки зрения распараллеливания, можно управлять с помощью нескольких переменных окружения\&. За деталями обратитесь к
\m[blue]\fBспецификации OpenMP API\fR\m[]\&\s-2\u[4]\d\s+2\&.
.RE
.PP
\fITMPDIR\fR
.RS 4
\fBpdf2djvu\fR
интенсивно использует временные файлы\&. Программа сохраняет их в каталоге заданном этой переменной\&. По умолчанию
/tmp\&.
.RE
.SH "ЯЗЫК ШАБЛОНОВ"
.SS "Синтаксис шаблонов"
.PP
Язык шаблонов использует как образец
\m[blue]\fBсинтаксис форматирования строк в Python\fR\m[]\&\s-2\u[5]\d\s+2\&.
.PP
Шаблон \(em это текст, который содержит
поля, окружённые фигурными скобками
{}\&. Когда шаблон применяется, поля заменяются соответствующим образом отформатированными значениями\&. Кроме того,
{{
и
}}
заменяются одиночными
{
и
}
соответственно\&.
.SS "Синтаксис полей"
.PP
Каждое поле состоит из имени переменной, за которым может следовать сдвиг (не обязательно) и спецификация формата (не обязательно)\&.
.PP
Сдвиг \(em целое число со знаком (т\&. е\&. начинающееся на
+
or
\-)\&.
.PP
Формат спецификации включает двоеточие, а затем спецификатор ширины поля\&.
.PP
Спецификатор ширины поля \(em это целое десятичное число определяющее минимальную ширину поля\&. Если не указано, тогда ширина поля вычисляется по содержимому\&. Предшествующий спецификатору знак нуля (0) делает возможным заполнение нулями\&.
.PP
После спецификатора ширины поля может располагаться знак звёздочки (*), что увеличивает минимальную ширину поля до максимально возможной длины переменной\&.
.SS "Доступные переменные"
.PP
\fIdpage\fR
.RS 4
Количество страниц в документе DjVu\&.
.RE
.PP
\fIpage\fR, \fIspage\fR
.RS 4
Количество страниц в документе PDF\&.
.RE
.PP
\fIlabel\fR
.RS 4
Метка страницы (логический номер страницы) в документе PDF\&.
.sp
Эта переменная доступна только для заголовков страницы\&.
.RE
.SH "ДЕТАЛИ РЕАЛИЗАЦИИ"
.SS "Алгоритм разделения слоёв"
.PP
Если не используется параметр
\fB\-\-monochrome\fR, pdf2djvu использует следующий простой алгоритм:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Для каждой страницы сделать следующее:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Преобразовать страницу в растровое изображение обычным порядком\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Преобразовать страницу в другое растровое изображение пропуская следующие элементы страницы:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
текст,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
растровые изображения с глубиной 1 бит на пиксел,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
векторные элементы (за исключением больших заполненных площадей)\&.
.RE
.sp
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Сравнить оба изображения, пиксел за пикселом:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Если их цвета совпадают, классифицировать пиксел как часть фонового слоя\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
В противоположном случае классифицировать пиксел как часть слоя переднего плана\&.
.RE
.sp
.RE
.sp
.RE
.sp
.SH "СООБЩЕНИЯ ОБ ОШИБКАХ"
.PP
Если вы нашли ошибку в pdf2djvu, сообщите о ней в
\m[blue]\fBбаг\-трекер\fR\m[]\&\s-2\u[6]\d\s+2
или в
\m[blue]\fBсписок рассылки\fR\m[]\&\s-2\u[7]\d\s+2\&.
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBdjvu\fR(1),
\fBdjvudigital\fR(1),
\fBcsepdjvu\fR(1)
.SH "ПРИМЕЧАНИЯ"
.IP " 1." 4
RFC 3999
.RS 4
\%https://www.ietf.org/rfc/rfc3339
.RE
.IP " 2." 4
NFKC
.RS 4
\%https://unicode.org/reports/tr15/
.RE
.IP " 3." 4
Alphabetic Presentation Forms block
.RS 4
\%https://unicode.org/charts/PDF/UFB00.pdf
.RE
.IP " 4." 4
спецификации OpenMP API
.RS 4
\%https://www.openmp.org/specifications/
.RE
.IP " 5." 4
синтаксис форматирования строк в Python
.RS 4
\%https://docs.python.org/2/library/string.html#format-string-syntax
.RE
.IP " 6." 4
баг-трекер
.RS 4
\%https://github.com/jwilk/pdf2djvu/issues
.RE
.IP " 7." 4
список рассылки
.RS 4
\%https://groups.io/g/pdf2djvu
.RE
